Move CDI extension to Concurrency RI project
eclipse-ee4j/concurrency-ri pull request #55
Opened 2022-06-13 09:15 UTC by arjantijms

Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

2022-06-13 14:17 UTC, smillidge commented
This is Payara code relicensed to the RI under the EPL. That needs to be done by a Payara Eclipse member authorised to do so for correct IP flow.

2022-06-13 14:19 UTC, smillidge requested changes
Needs to be done by a Payara committer.

2022-06-13 14:21 UTC, arjantijms commented
> This is Payara code relicensed to the RI under the EPL. 

That's right, hence why I only tagged Petr as reviewer, and of course mentioned Payara as the copyright holder. Feel free though to copy the PR and resubmit it. This is done (as mentioned on the mailing list) as a convenience, so you essentially only have to give permission.

2022-06-18 20:52 UTC, smillidge commented
Superseded by #56

2022-06-18 20:52 UTC, closed without merging